# Generated by Django 4.1.6 on 2023-03-02 21:12

import accounts_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_manager', '0002_alter_useraccount_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar/avatar.jpg', max_length=255, null=True, upload_to=accounts_manager.models.UserAccount.avatar_path),
        ),
    ]
