# Generated by Django 4.1.6 on 2023-03-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_manager', '0003_alter_useraccount_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='avatar',
        ),
    ]
