# Generated by Django 4.1.6 on 2023-03-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_manager', '0005_useraccount_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
