# Generated by Django 4.1.6 on 2023-03-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_description',
        ),
    ]
